---
# Source: example-consumer/charts/platform-service/templates/virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  gateways:
  - mesh
  http:
  - name: "httpbin-internal-route"
    route:
    - destination:
        host: "httpbin"
    - destination:
        host: "httpbin"
    retries:
      attempts: 3
